# Generated by Django 4.0.5 on 2022-06-15 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=200)),
                ('pilihan_a', models.CharField(max_length=200)),
                ('pilihan_b', models.CharField(max_length=200)),
                ('pilihan_c', models.CharField(max_length=200)),
                ('pilihan_d', models.CharField(max_length=200)),
                ('kunci_jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Bank Soal',
            },
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Peserta',
            },
        ),
        migrations.CreateModel(
            name='NilaiEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nilai', models.IntegerField()),
                ('peserta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz1r.peserta')),
            ],
            options={
                'verbose_name_plural': 'Nilai Evaluasi',
            },
        ),
        migrations.CreateModel(
            name='HasilEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lembar_evaluasi', models.CharField(max_length=10)),
                ('jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('status', models.CharField(choices=[('Benar', 'Benar'), ('Salah', 'Salah')], max_length=5)),
                ('nilai', models.IntegerField()),
                ('bank_soal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz1r.banksoal')),
                ('peserta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz1r.peserta')),
            ],
            options={
                'verbose_name_plural': 'Hasil Evaluasi',
            },
        ),
    ]
